In [90]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import geopandas as gpd
%matplotlib inline

In [91]:
df = pd.read_csv('./gp1.csv')
df

,District,Block,Panchyat,Code,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20
0,Sundargarh,BALISANKARA,Balisankara,121521.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Sundargarh,BALISANKARA,Bandega,121522.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Sundargarh,BALISANKARA,Bandhabahal,121523.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Sundargarh,BALISANKARA,Birkaldihi,121524.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Sundargarh,BALISANKARA,Damkuda,121740.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
997,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Create a DF from a df for specific columns. by passing a list of columns to df.

In [92]:
df1 = df[['District','Block','Panchyat','Code']].copy()

In [93]:
df1.head()

     District        Block     Panchyat      Code
0  Sundargarh  BALISANKARA  Balisankara  121521.0
1  Sundargarh  BALISANKARA      Bandega  121522.0
2  Sundargarh  BALISANKARA  Bandhabahal  121523.0
3  Sundargarh  BALISANKARA   Birkaldihi  121524.0
4  Sundargarh  BALISANKARA      Damkuda  121740.0

In [94]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   District  291 non-null    object
 1   Block     291 non-null    object
 2   Panchyat  291 non-null    object
 3   Code      291 non-null    float64
dtypes: float64(1), object(3)
memory usage: 31.4+ KB

### join string by + operator OR "".join() method.

In [95]:
df1['Panchyat'] = df1['Panchyat'] + ' , Sundergarh ,Odisha ,India'
df1.head()

     District        Block                                 Panchyat      Code
0  Sundargarh  BALISANKARA  Balisankara , Sundergarh ,Odisha ,India  121521.0
1  Sundargarh  BALISANKARA      Bandega , Sundergarh ,Odisha ,India  121522.0
2  Sundargarh  BALISANKARA  Bandhabahal , Sundergarh ,Odisha ,India  121523.0
3  Sundargarh  BALISANKARA   Birkaldihi , Sundergarh ,Odisha ,India  121524.0
4  Sundargarh  BALISANKARA      Damkuda , Sundergarh ,Odisha ,India  121740.0

In [96]:
df1.isna().sum()

District    709
Block       709
Panchyat    709
Code        709
dtype: int64

In [97]:
df1.shape

(1000, 4)

### You can use DataFrame.any with parameter axis=1 for check at least one True in row by DataFrame.isna().

In [98]:
df2 = df1[df1.isna().any(axis=1)]
df2

    District Block Panchyat  Code
291      NaN   NaN      NaN   NaN
292      NaN   NaN      NaN   NaN
293      NaN   NaN      NaN   NaN
294      NaN   NaN      NaN   NaN
295      NaN   NaN      NaN   NaN
..       ...   ...      ...   ...
995      NaN   NaN      NaN   NaN
996      NaN   NaN      NaN   NaN
997      NaN   NaN      NaN   NaN
998      NaN   NaN      NaN   NaN
999      NaN   NaN      NaN   NaN

[709 rows x 4 columns]

In [99]:
df1.dropna(inplace=True)

In [100]:
df1.shape

(291, 4)

In [101]:
df1.head()

     District        Block                                 Panchyat      Code
0  Sundargarh  BALISANKARA  Balisankara , Sundergarh ,Odisha ,India  121521.0
1  Sundargarh  BALISANKARA      Bandega , Sundergarh ,Odisha ,India  121522.0
2  Sundargarh  BALISANKARA  Bandhabahal , Sundergarh ,Odisha ,India  121523.0
3  Sundargarh  BALISANKARA   Birkaldihi , Sundergarh ,Odisha ,India  121524.0
4  Sundargarh  BALISANKARA      Damkuda , Sundergarh ,Odisha ,India  121740.0

In [102]:
df1['Panchyat'].unique()

array(['Balisankara , Sundergarh ,Odisha ,India',
       'Bandega , Sundergarh ,Odisha ,India',
       'Bandhabahal , Sundergarh ,Odisha ,India',
       'Birkaldihi , Sundergarh ,Odisha ,India',
       'Damkuda , Sundergarh ,Odisha ,India',
       'Deobhubanpur , Sundergarh ,Odisha ,India',
       'Deogaon , Sundergarh ,Odisha ,India',
       'Jaisore , Sundergarh ,Odisha ,India',
       'Jamuna , Sundergarh ,Odisha ,India',
       'Karmabahal , Sundergarh ,Odisha ,India',
       'Karumkel , Sundergarh ,Odisha ,India',
       'Kinjirkela , Sundergarh ,Odisha ,India',
       'Kiralaga , Sundergarh ,Odisha ,India',
       'Kusummura , Sundergarh ,Odisha ,India',
       'Lulukidihi , Sundergarh ,Odisha ,India',
       'Rampur , Sundergarh ,Odisha ,India',
       'Sagbahal , Sundergarh ,Odisha ,India',
       'Saunamura , Sundergarh ,Odisha ,India',
       'Subdega , Sundergarh ,Odisha ,India',
       'Talsora , Sundergarh ,Odisha ,India',
       'Tengargaon , Sundergarh ,Odisha ,India',
       'Tildega , Sundergarh ,Odisha ,India',
       'Tileikani , Sundergarh ,Odisha ,India',
       'Tumlia , Sundergarh ,Odisha ,India',
       'Barangakachhar , Sundergarh ,Odisha ,India',
       'Bargaon , Sundergarh ,Odisha ,India',
       'Bhoipali , Sundergarh ,Odisha ,India',
       'Dandajamira , Sundergarh ,Odisha ,India',
       'Ekma , Sundergarh ,Odisha ,India',
       'Fulbari , Sundergarh ,Odisha ,India',
       'Itma , Sundergarh ,Odisha ,India',
       'Jarngloi , Sundergarh ,Odisha ,India',
       'Pamra , Sundergarh ,Odisha ,India',
       'Rungaon , Sundergarh ,Odisha ,India',
       'Sahajbahal , Sundergarh ,Odisha ,India',
       'Tikilipara , Sundergarh ,Odisha ,India',
       'Tudalaga , Sundergarh ,Odisha ,India',
       'Bad Bambua , Sundergarh ,Odisha ,India',
       'Bandamunda , Sundergarh ,Odisha ,India',
       'Bhalulata , Sundergarh ,Odisha ,India',
       'Bisra , Sundergarh ,Odisha ,India',
       'Dareikela , Sundergarh ,Odisha ,India',
       'Jagada , Sundergarh ,Odisha ,India',
       'Jamsera , Sundergarh ,Odisha ,India',
       'Jaroikela , Sundergarh ,Odisha ,India',
       'Jhirpani , Sundergarh ,Odisha ,India',
       'Kapatmunda , Sundergarh ,Odisha ,India',
       'Manko , Sundergarh ,Odisha ,India',
       'Santoshpur , Sundergarh ,Odisha ,India',
       'Thethoiposh , Sundergarh ,Odisha ,India',
       'Tulsikani , Sundergarh ,Odisha ,India',
       'Udusu , Sundergarh ,Odisha ,India',
       'Badgogua , Sundergarh ,Odisha ,India',
       'Bhalupani , Sundergarh ,Odisha ,India',
       'Bonaigarh , Sundergarh ,Odisha ,India',
       'Bonaikela , Sundergarh ,Odisha ,India',
       'Govindpur , Sundergarh ,Odisha ,India',
       'Jakeikela , Sundergarh ,Odisha ,India',
       'Jhirdapali , Sundergarh ,Odisha ,India',
       'Kasada , Sundergarh ,Odisha ,India',
       'Kenaveta , Sundergarh ,Odisha ,India',
       'Kendrikela , Sundergarh ,Odisha ,India',
       'Pithachore , Sundergarh ,Odisha ,India',
       'Ruguda , Sundergarh ,Odisha ,India',
       'Sarsara Balang , Sundergarh ,Odisha ,India',
       'Banki , Sundergarh ,Odisha ,India',
       'Bhaluidungri , Sundergarh ,Odisha ,India',
       'Chandiposh , Sundergarh ,Odisha ,India',
       'Gurundia , Sundergarh ,Odisha ,India',
       'Jarda , Sundergarh ,Odisha ,India',
       'Kucheita , Sundergarh ,Odisha ,India',
       'Kundheidiha , Sundergarh ,Odisha ,India',
       'Narendra , Sundergarh ,Odisha ,India',
       'Pankdihi , Sundergarh ,Odisha ,India',
       'Sole , Sundergarh ,Odisha ,India',
       'Tamada , Sundergarh ,Odisha ,India',
       'Tamporkela , Sundergarh ,Odisha ,India',
       'Ankelbira , Sundergarh ,Odisha ,India',
       'Balinga , Sundergarh ,Odisha ,India',
       'Duduka , Sundergarh ,Odisha ,India',
       'Durubaga , Sundergarh ,Odisha ,India',
       'Garjanjore , Sundergarh ,Odisha ,India',
       'Gopalpur , Sundergarh ,Odisha ,India',
       'Hemgir , Sundergarh ,Odisha ,India',
       'Jharpalam , Sundergarh ,Odisha ,India',
       'Julumbahal , Sundergarh ,Odisha ,India',
       'Kanaktura , Sundergarh ,Odisha ,India',
       'Kanika , Sundergarh ,Odisha ,India',
       'Kendudihi , Sundergarh ,Odisha ,India',
       'Kuchedega , Sundergarh ,Odisha ,India',
       'Laikera , Sundergarh ,Odisha ,India',
       'Munderkhei , Sundergarh ,Odisha ,India',
       'Sanghumunda , Sundergarh ,Odisha ,India',
       'Sumura , Sundergarh ,Odisha ,India',
       'Topria , Sundergarh ,Odisha ,India',
       'Tumulia , Sundergarh ,Odisha ,India',
       'Bimalagarh , Sundergarh ,Odisha ,India',
       'Chordhara , Sundergarh ,Odisha ,India',
       'Dengula , Sundergarh ,Odisha ,India',
       'Gopna , Sundergarh ,Odisha ,India',
       'Jamudihi , Sundergarh ,Odisha ,India',
       'K.Balang , Sundergarh ,Odisha ,India',
       'Kalta , Sundergarh ,Odisha ,India',
       'Koira , Sundergarh ,Odisha ,India',
       'Malda , Sundergarh ,Odisha ,India',
       'Patmund , Sundergarh ,Odisha ,India',
       'Relhatu , Sundergarh ,Odisha ,India',
       'Soyamba , Sundergarh ,Odisha ,India',
       'Andali , Sundergarh ,Odisha ,India',
       'Andhari , Sundergarh ,Odisha ,India',
       'Dalki , Sundergarh ,Odisha ,India',
       'Damarjore , Sundergarh ,Odisha ,India',
       'Hatibari , Sundergarh ,Odisha ,India',
       'Jalangbira , Sundergarh ,Odisha ,India',
       'Jayadega , Sundergarh ,Odisha ,India',
       'Jharbeda , Sundergarh ,Odisha ,India',
       'Jhunmur , Sundergarh ,Odisha ,India',
       'Kacharu , Sundergarh ,Odisha ,India',
       'Kadobahal , Sundergarh ,Odisha ,India',
       'Kalosihiria , Sundergarh ,Odisha ,India',
       'Kardega , Sundergarh ,Odisha ,India',
       'Karkatnasa , Sundergarh ,Odisha ,India',
       'Khukundubahal , Sundergarh ,Odisha ,India',
       'Korama , Sundergarh ,Odisha ,India',
       'Kuarmunda , Sundergarh ,Odisha ,India',
       'Kumjharia , Sundergarh ,Odisha ,India',
       'Majhapur , Sundergarh ,Odisha ,India',
       'Padampur , Sundergarh ,Odisha ,India',
       'Pratappur , Sundergarh ,Odisha ,India',
       'Puturikhaman , Sundergarh ,Odisha ,India',
       'Raiboga , Sundergarh ,Odisha ,India',
       'Salangabahal , Sundergarh ,Odisha ,India',
       'Amgova , Sundergarh ,Odisha ,India',
       'Biringatali , Sundergarh ,Odisha ,India',
       'Gangajal , Sundergarh ,Odisha ,India',
       'Gyanpali , Sundergarh ,Odisha ,India',
       'Kandeimunda , Sundergarh ,Odisha ,India',
       'Katang , Sundergarh ,Odisha ,India',
       'Khatkurbahal , Sundergarh ,Odisha ,India',
       'Kiringsira , Sundergarh ,Odisha ,India',
       'Kutra , Sundergarh ,Odisha ,India',
       'Nuagaon , Sundergarh ,Odisha ,India',
       'Panchara , Sundergarh ,Odisha ,India',
       'Purkapali , Sundergarh ,Odisha ,India',
       'Rajabasa , Sundergarh ,Odisha ,India',
       'Tarkera , Sundergarh ,Odisha ,India',
       'Tunmura , Sundergarh ,Odisha ,India',
       'Badpuranpani , Sundergarh ,Odisha ,India',
       'Bhatuda , Sundergarh ,Odisha ,India',
       'Daleisara , Sundergarh ,Odisha ,India',
       'Darjing , Sundergarh ,Odisha ,India',
       'Fuljhar , Sundergarh ,Odisha ,India',
       'Haldikudar , Sundergarh ,Odisha ,India',
       'Kaleiposh , Sundergarh ,Odisha ,India',
       'Khuntagaon , Sundergarh ,Odisha ,India',
       'Kuliposh , Sundergarh ,Odisha ,India',
       'Kundheikela , Sundergarh ,Odisha ,India',
       'Kurda , Sundergarh ,Odisha ,India',
       'Lahunipara , Sundergarh ,Odisha ,India',
       'Mahulpada , Sundergarh ,Odisha ,India',
       'Rajamunda , Sundergarh ,Odisha ,India',
       'Sankela , Sundergarh ,Odisha ,India',
       'Sankhaposh , Sundergarh ,Odisha ,India',
       'Talbahali , Sundergarh ,Odisha ,India',
       'Bad-Dalki , Sundergarh ,Odisha ,India',
       'Balanda , Sundergarh ,Odisha ,India',
       'Birja , Sundergarh ,Odisha ,India',
       'Birkera , Sundergarh ,Odisha ,India',
       'Chikatmati , Sundergarh ,Odisha ,India',
       'Garjan , Sundergarh ,Odisha ,India',
       'Hatibandha , Sundergarh ,Odisha ,India',
       'Jadakudar , Sundergarh ,Odisha ,India',
       'Jalda , Sundergarh ,Odisha ,India',
       'Jhartarang , Sundergarh ,Odisha ,India',
       'Kulunga , Sundergarh ,Odisha ,India',
       'Lathikata , Sundergarh ,Odisha ,India',
       'Mundajore , Sundergarh ,Odisha ,India',
       'Ramjodi , Sundergarh ,Odisha ,India',
       'Suidihi , Sundergarh ,Odisha ,India',
       'Tainsar , Sundergarh ,Odisha ,India',
       'Alapaka , Sundergarh ,Odisha ,India',
       'Badbanga , Sundergarh ,Odisha ,India',
       'Chhatenpali , Sundergarh ,Odisha ,India',
       'Darliput , Sundergarh ,Odisha ,India',
       'Dumabahal , Sundergarh ,Odisha ,India',
       'Giringkela , Sundergarh ,Odisha ,India',
       'Gundiadihi , Sundergarh ,Odisha ,India',
       'Hurmei , Sundergarh ,Odisha ,India',
       'Jhurimal , Sundergarh ,Odisha ,India',
       'Kulabira , Sundergarh ,Odisha ,India',
       'Lephiripara , Sundergarh ,Odisha ,India',
       'Masabira , Sundergarh ,Odisha ,India',
       'Raibaga , Sundergarh ,Odisha ,India',
       'Raidihi , Sundergarh ,Odisha ,India',
       'Rajbahal , Sundergarh ,Odisha ,India',
       'Sarafgarh , Sundergarh ,Odisha ,India',
       'Sargipali , Sundergarh ,Odisha ,India',
       'Ankurpali , Sundergarh ,Odisha ,India',
       'Badajojoda , Sundergarh ,Odisha ,India',
       'Bagdega , Sundergarh ,Odisha ,India',
       'Barilepta , Sundergarh ,Odisha ,India',
       'Chitapedi , Sundergarh ,Odisha ,India',
       'Jahaditoli , Sundergarh ,Odisha ,India',
       'Kandarkela , Sundergarh ,Odisha ,India',
       'Khuntgaon , Sundergarh ,Odisha ,India',
       'Limida , Sundergarh ,Odisha ,India',
       'Lukumbeda , Sundergarh ,Odisha ,India',
       'Menmena , Sundergarh ,Odisha ,India',
       'Purunapani , Sundergarh ,Odisha ,India',
       'Sorda , Sundergarh ,Odisha ,India',
       'Teterkela , Sundergarh ,Odisha ,India',
       'Urmai , Sundergarh ,Odisha ,India',
       'Alanda , Sundergarh ,Odisha ,India',
       'Buchukupara , Sundergarh ,Odisha ,India',
       'Budha-Am , Sundergarh ,Odisha ,India',
       'Chungimati , Sundergarh ,Odisha ,India',
       'Jareikela , Sundergarh ,Odisha ,India',
       'Kesramal , Sundergarh ,Odisha ,India',
       'Kukuda , Sundergarh ,Odisha ,India',
       'Kunmuru , Sundergarh ,Odisha ,India',
       'Kutunia , Sundergarh ,Odisha ,India',
       'Laing , Sundergarh ,Odisha ,India',
       'Malidihi , Sundergarh ,Odisha ,India',
       'Panposh , Sundergarh ,Odisha ,India',
       'Baragarh , Sundergarh ,Odisha ,India',
       'Bhadabahal , Sundergarh ,Odisha ,India',
       'Bhasma , Sundergarh ,Odisha ,India',
       'Birbira , Sundergarh ,Odisha ,India',
       'Deuli , Sundergarh ,Odisha ,India',
       'Karla , Sundergarh ,Odisha ,India',
       'Kinjirma , Sundergarh ,Odisha ,India',
       'Kirei , Sundergarh ,Odisha ,India',
       'Kulta , Sundergarh ,Odisha ,India',
       'Kundukela , Sundergarh ,Odisha ,India',
       'Lahandabud , Sundergarh ,Odisha ,India',
       'Lankahuda , Sundergarh ,Odisha ,India',
       'Ledhimarg , Sundergarh ,Odisha ,India',
       'Majhapara , Sundergarh ,Odisha ,India',
       'Masonikani , Sundergarh ,Odisha ,India',
       'Salepali , Sundergarh ,Odisha ,India',
       'Hamirpur , Sundergarh ,Odisha ,India',
       'Karamdihi , Sundergarh ,Odisha ,India',
       'Kukuridihi , Sundergarh ,Odisha ,India',
       'Kulab , Sundergarh ,Odisha ,India',
       'Patrapali , Sundergarh ,Odisha ,India',
       'Rajpur , Sundergarh ,Odisha ,India',
       'Ratanpur , Sundergarh ,Odisha ,India',
       'Sublaya , Sundergarh ,Odisha ,India',
       'Gambhardihi , Sundergarh ,Odisha ,India',
       'Jogimal , Sundergarh ,Odisha ,India',
       'Kiripsira , Sundergarh ,Odisha ,India',
       'Mahulpali , Sundergarh ,Odisha ,India',
       'Mangaspur , Sundergarh ,Odisha ,India',
       'Megdega , Sundergarh ,Odisha ,India',
       'Nialipali , Sundergarh ,Odisha ,India',
       'Remenda , Sundergarh ,Odisha ,India',
       'Tangarpali , Sundergarh ,Odisha ,India',
       'Tasladihi , Sundergarh ,Odisha ,India',
       'Ujjalpur , Sundergarh ,Odisha ,India'], dtype=object)

In [103]:
df1['Panchyat'].nunique()

259

In [104]:
df1.shape

(291, 4)

### all duplicated rows got . but searching duplicacy in column 'Panchyat'.

In [105]:
df1[df1['Panchyat'].duplicated(keep=False)]

       District        Block                               Panchyat      Code
4    Sundargarh  BALISANKARA    Damkuda , Sundergarh ,Odisha ,India  121740.0
6    Sundargarh  BALISANKARA    Deogaon , Sundergarh ,Odisha ,India  121741.0
7    Sundargarh  BALISANKARA    Jaisore , Sundergarh ,Odisha ,India  121743.0
8    Sundargarh  BALISANKARA     Jamuna , Sundergarh ,Odisha ,India  121744.0
10   Sundargarh  BALISANKARA   Karumkel , Sundergarh ,Odisha ,India  121746.0
..          ...          ...                                    ...       ...
276  Sundargarh  TANGARPALLI   Jhurimal , Sundergarh ,Odisha ,India  121699.0
278  Sundargarh  TANGARPALLI  Kanaktura , Sundergarh ,Odisha ,India  121609.0
284  Sundargarh  TANGARPALLI    Raibaga , Sundergarh ,Odisha ,India  121703.0
285  Sundargarh  TANGARPALLI    Raidihi , Sundergarh ,Odisha ,India  121704.0
287  Sundargarh  TANGARPALLI  Sargipali , Sundergarh ,Odisha ,India  121707.0

[62 rows x 4 columns]

In [106]:
df1.shape

(291, 4)

### .drop_duplicates()  u use subset for all columns having duplicated items to drop.

In [107]:
df1.drop_duplicates(subset=['Panchyat'], keep=False, inplace=True)

In [108]:
df1.shape

(229, 4)

In [109]:
df1.head()

     District        Block                                  Panchyat      Code
0  Sundargarh  BALISANKARA   Balisankara , Sundergarh ,Odisha ,India  121521.0
1  Sundargarh  BALISANKARA       Bandega , Sundergarh ,Odisha ,India  121522.0
2  Sundargarh  BALISANKARA   Bandhabahal , Sundergarh ,Odisha ,India  121523.0
3  Sundargarh  BALISANKARA    Birkaldihi , Sundergarh ,Odisha ,India  121524.0
5  Sundargarh  BALISANKARA  Deobhubanpur , Sundergarh ,Odisha ,India  121525.0

In [111]:
#pip install geopy    (help to get latitude and longitude)
from geopy.geocoders import Nominatim

In [112]:
geolocator = Nominatim(user_agent='app',timeout=None)
geolocator

In [115]:
lat = []
lon = []

for name in df1['Panchyat']:
    location = geolocator.geocode(name)
    
    if location is None:
        lat.append(np.nan)
        lon.append(np.nan)
    else:
        lat.append(location.latitude)
        lon.append(location.longitude)

In [116]:
lat

[nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 21.8200393,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan]

In [ ]:
df1['lat'] = lat
df1['lon'] = lon

In [ ]:
df1